version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: school-management-mysql
    ports:
      - 3310:3306
    environment:
      - MYSQL_DATABASE=school-management-api
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - student-api

volumes:
  my_db:

